# Generated by Django 5.1.6 on 2025-03-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_customer_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orederplaced',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='orederplaced',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orederplaced',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='OrederPlaced',
        ),
    ]
